version: "3.7"

services:
  caddy:
    build:
      context: mycaddy/
    container_name: caddy
    restart: unless-stopped
    ports:
      - "4433:4433"
      - "4433:4433/udp"
    volumes:
      - /data/app/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/app/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    network_mode: bridge
volumes:
  caddy_data:
  caddy_config: